# Generated by Django 4.2.6 on 2024-05-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_vih', models.CharField(max_length=50)),
                ('ist_syphilis', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result_positive', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ist_analyses', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabete_glucose', models.FloatField()),
                ('diabete_hba1c', models.FloatField()),
                ('date', models.DateField()),
                ('result_positive', models.BooleanField()),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_analyses', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CommonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_blood_cells', models.FloatField()),
                ('white_blood_cells', models.FloatField()),
                ('platelets', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='common_analyses', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CholesterolAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chol_total', models.FloatField()),
                ('chol_hdl', models.FloatField()),
                ('chol_ldl', models.FloatField()),
                ('chol_triglycerides', models.FloatField()),
                ('date', models.DateField()),
                ('result_positive', models.BooleanField()),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol_analyses', to='users.patient')),
            ],
        ),
    ]
