# Generated by Django 4.2.6 on 2024-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cholesterolanalysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='commonanalysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diabetesanalysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='istanalysis',
            name='patient',
        ),
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='patientname',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='patientname',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='patientname',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='patientname',
            field=models.CharField(default=''),
        ),
    ]
