# Generated by Django 4.2.6 on 2024-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='instructions',
            field=models.TextField(),
        ),
    ]
