# Generated by Django 4.2.6 on 2024-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_rendezvous_patient_rendezvous_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='instructions',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
